---
title: "Atmo_HW_6"
author: "Joseph Crockett"
date: "March 2, 2016"
output: html_document
---
Joseph Crockett
March 1, 2016
ES 292: Atmospheric Modeling
Homework 6

7.2 and 7.*1

7.2a Code
```{r }
u_wst_h <- 3 #m/s
u_est_h <- 1 #m/s
v_nth_h <- 2 #m/s
v_sth_h <- 1 #m/s
pi_wst_h <- 745 #hPa
pi_est_h <- 752 #hPa
pi_nth_h <- 754 #hPa
pi_sth_h <- 746 #hPa
pi_cen_h <- mean(pi_wst_h, pi_est_h, pi_nth_h, pi_sth_h) #hPa
pi_cen <- pi_cen_h
Re <- 6.371 * 10^6 #m
w <- 45 * pi/180 
del_w <- 4 * pi/180
del_l <- 5 * pi/180
del_sig <- .05
hh <- 5 * 60 * 1 #minutes * seconds * #timesteps
q_wst_h <- .0062 #kg/kg
q_est_h <- .0047 #kg/kg
q_nth_h <- .0064 #kg/kg
q_sth_h <- .0054 #kg/kg
q_low_h <- .005 #kg/kg
q_up_h <- 006 #kg/kg
q_cen_h <- mean(q_wst_h, q_est_h, q_nth_h, q_sth_h, q_low_h, q_up_h)
sig_low <- -4.58*10^(-6) #sig/s
sig_up <- -6.11 * 10^(-6) #sig/s







F_est_h <- pi_est_h * u_est_h * Re * del_w
F_wst_h <- pi_wst_h * u_wst_h * Re * del_w
G_nth_h <- pi_nth_h * v_nth_h * Re * cos(w) * del_l
G_sth_h <- pi_sth_h * v_sth_h * Re * cos(w) * del_l


q_cen_t <- function(h){
  init <- ((pi_cen_h * q_cen_h)/ pi_cen)  
   tme <- (h / (pi_cen * Re^2 * cos(w) * del_l * del_w)) 
   fst<- ((F_wst_h * (q_wst_h + q_cen_h)/2) - 
      (F_est_h * (q_est_h + q_cen_h)/2)) + 
      ( (G_nth_h * (q_nth_h + q_cen_h)/2) - 
          (G_sth_h * (q_sth_h + q_cen_h)/2) )   
 lst <- (pi_cen * Re^2 * cos(w) * del_l * del_w * 
      (
      ((sig_low * q_low_h) - (sig_up * q_up_h))/del_sig
      )
    )
 
 
 return(init + tme*(fst + lst))
}

q_cen_t(h = (5*60*1))

```
7.2b
```{r}
theta_wst_h <- 297 #k
theta_est_h <- 298 #k
theta_sth_h <- 300 #k
theta_nth_h <- 299 #k
theta_low_h <- 298.3 #k
theta_up_h <- 298.7 #k
theta_cen_h <- mean(theta_wst_h,theta_est_h,theta_sth_h,theta_nth_h, theta_low_h, theta_up_h)

theta_cen_t <- function(h){
  init <- ((pi_cen_h * theta_cen_h)/ pi_cen)  
   tme <- (h / (pi_cen * Re^2 * cos(w) * del_l * del_w))
   fst<- ((F_wst_h * (theta_wst_h + theta_cen_h)/2) - 
      (F_est_h * (theta_est_h + theta_cen_h)/2)) + 
      ( (G_nth_h * (theta_nth_h + theta_cen_h)/2) - 
          (G_sth_h * (theta_sth_h + theta_cen_h)/2) )
    lst <- (pi_cen * Re^2 * cos(w) * del_l * del_w * 
      (
      ((sig_low * theta_low_h) - (sig_up * theta_up_h))/del_sig
      )
    )
  
 return(init + tme*(fst + lst))
}

theta_cen_t(h = (5*60*1))  

```